Aula 19 - 2021.06.10 - Funções

/*
NA AULA 11 (EXEMPLO DE RELATÓRIOS) TEMOS O "RELATÓRIO DE VENDAS PERCENTUAL POR SABOR". CRIE UMA FUNÇÃO QUE AO INSERIR O TIPO DE 
EMBALAGEM A FUNÇÃO RETORNE UMA TABELA COM TODOS OS ANOS, SEU FATURAMENTO E A PARTICIPAÇÃO EM PERCENTUAL.*/



SELECT * FROM 
(SELECT AUX1.EMBALAGEM, AUX1.ANO,FORMAT(AUX1.FATURAMENTO,'C','PT-BR')AS 'FATURAMENTO', CONVERT (VARCHAR,ROUND((AUX1.FATURAMENTO/AUX2.[FATURAMENTO ANUAL])*100,2))+' %' AS 'PERCENTUAL' FROM
(SELECT TP.EMBALAGEM, YEAR (NF.DATA) AS 'ANO', SUM (INF.QUANTIDADE * INF.PREÇO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN[TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY TP.EMBALAGEM, YEAR (NF.DATA))AUX1

INNER JOIN (SELECT YEAR (NF.DATA) AS 'ANO', SUM(INF.QUANTIDADE*INF.PREÇO) AS 'FATURAMENTO ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
INNER JOIN[TABELA DE NOTAS FISCAIS]NF
ON INF.NUMERO = NF.NUMERO
INNER JOIN [TABELA DE PRODUTOS]TP
ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
GROUP BY YEAR (NF.DATA))AUX2

ON AUX1.ANO = AUX2.ANO)AUX3
WHERE AUX3.EMBALAGEM = 'Lata'


CREATE FUNCTION [dbo].[FuncFaturamentoPercentual] (@EMBALAGEM VARCHAR (50), @FATURAMENTO FLOAT, @PERCENTUAL FLOAT, @ANO DATE) RETURNS TABLE
AS
	RETURN
		SELECT AUX1.EMBALAGEM,AUX1.ANO,ROUND(AUX1.[FATURAMENTO],2) AS 'FATURAMENTO', CONVERT (VARCHAR,ROUND((AUX1.[FATURAMENTO]/AUX2.[FATURAMENTO_ANUAL])*100,2))+ '%' AS 'PERCENTUAL' FROM
			(SELECT TP.[EMBALAGEM], YEAR(NF.DATA) AS 'ANO',SUM (INF.QUANTIDADE*INF.PREÇO) AS 'FATURAMENTO' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
			INNER JOIN [TABELA DE NOTAS FISCAIS]NF
			ON INF.NUMERO = NF.NUMERO 
			INNER JOIN [TABELA DE PRODUTOS]TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO] 
			GROUP BY TP.EMBALAGEM,YEAR(NF.DATA))AUX1
			INNER JOIN
			(SELECT YEAR(NF.DATA) AS 'ANO',SUM (INF.QUANTIDADE*INF.PREÇO) AS 'FATURAMENTO_ANUAL' FROM [TABELA DE ITENS NOTAS FISCAIS]INF
			INNER JOIN [TABELA DE NOTAS FISCAIS]NF
			ON INF.NUMERO = NF.NUMERO 
			INNER JOIN [TABELA DE PRODUTOS]TP
			ON INF.[CODIGO DO PRODUTO] = TP.[CODIGO DO PRODUTO]
			GROUP BY YEAR(NF.DATA))AUX2
			ON AUX1.ANO = AUX2.ANO
			WHERE AUX1.EMBALAGEM = 'PET'

